#!/usr/bin/env bash
# Generate prisma/migrations/0_init/migration.sql locally — same steps as
# .github/workflows/generate-baseline.yml, for when GitHub Actions can't run.
# Needs Node + network access to npm. Does not touch any database.
#
#   ./scripts/generate-baseline.sh && git add prisma/migrations/0_init && git commit -m "Add Prisma 0_init baseline"
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=prisma/migrations/0_init/migration.sql
if [ -f "$OUT" ]; then echo "$OUT already exists — nothing to do."; exit 0; fi

mkdir -p prisma/migrations/0_init
{
  echo "-- Baseline: full GridGuide schema as of commit 22fe0dd (before the Oct 2026 P0 changes)."
  echo "-- Generated by Prisma (migrate diff --from-empty). Replaces the old partial migration chain,"
  echo "-- which assumed tables originally created with 'prisma db push' (see prisma/migrations_archive/)."
  echo
  npx --yes prisma@5.14.0 migrate diff --from-empty \
    --to-schema-datamodel prisma/migrations_archive/schema-at-0_init.prisma --script
} > "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT") lines)."
